<h1><?php echo $this->locale->_("Products"); ?></h1>
<table class="table table-bordered table-hover">
    <thead class="thead-light">
        <tr>
            <th>#</th>
            <th><?php echo $this->locale->_("Name"); ?></th>
            <th><?php echo $this->locale->_("Description"); ?></th>
            <th><?php echo $this->locale->_("Tags"); ?></th>
            <th><?php echo $this->locale->_("Price"); ?></th>
            <th><?php echo $this->locale->_("Stock"); ?></th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="3"><?php echo $this->locale->_("Products quantity"); ?>: <?php echo $data->count(); ?></td>
        </tr>
    </tfoot>
    <tbody>
        <?php foreach ($data as $value) { ?>
            <tr>
                <td><?php echo $value->id; ?></td>
                <td><?php echo $value->name; ?></td>
                <td><?php echo $value->description; ?></td>
                <td><?php echo $value->tags; ?></td>
                <td><?php echo $value->price; ?></td>
                <td><?php echo $value->stock; ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>